### ISSUE TITLE
Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by hwairway** [kingmo888/rustdesk-api-server#127]
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      /bin/sh: 1: pkg-config: not found
      /bin/sh: 1: pkg-config: not found
      /bin/sh: 1: pkg-config: not found
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
      Trying pkg-config --exists libmariadb
      Command 'pkg-config --exists libmariadb' returned non-zero exit status 127.
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-7r8tpw89/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-7r8tpw89/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-7r8tpw89/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 155, in <module>
        File "<string>", line 49, in get_config_posix
        File "<string>", line 28, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by hwairway** [comment]
![Uploading 微信图片_20240827170705.png…]()

**Comment by hwairway** [comment]
Ubuntu 22.04 64位

**Comment by hwairway** [comment]
root@iZj6c4aagl789byrzsis3qZ:~# sudo apt-get install pkg-config
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pkg-config is already the newest version (0.29.2-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
root@iZj6c4aagl789byrzsis3qZ:~# pip3 install pkg-config
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement pkg-config (from versions: none)
ERROR: No matching distribution found for pkg-config

安装了，但是还是显示找不到合适的版本。。。

**Comment by hwairway** [comment]
root@iZj6c4aagl789byrzsis3qZ:~/rustdesk-api-server# sudo apt-get install pkg-config
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pkg-config is already the newest version (0.29.2-1ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 56 not upgraded.
root@iZj6c4aagl789byrzsis3qZ:~/rustdesk-api-server# pip3 install pkg-config
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement pkg-config (from versions: none)
ERROR: No matching distribution found for pkg-config
------------------------
安装完了，显示还是找不到   是路径问题吗。。。。

**Comment by hwairway** [comment]
安装了一个 数据库解决了  谢谢

**Comment by hwairway** [comment]
apt-get install libmysqlclient-dev
