### ISSUE TITLE
最新版本不能使用。

### ISSUE THREAD

**Issue by 1025766948** [kingmo888/rustdesk-api-server#144]
您的rustdesk-api-serverV1.4.7.1Source code(zip)下载后显示其实是1.4.9，在Ubuntu中可以使用。
您的rustdesk-api-serverV1.5.0Source code(zip)下载后显示其实是1.5.2，在Ubuntu中不能使用。
在1.52以后的版本都不能使用，提示如下信息。
root@hi3798mv100:/usr/share/rustdesk-api-server-1.5.2# pip install -r requirements.txt
Collecting django
  Using cached Django-4.2.16-py3-none-any.whl (8.0 MB)
Collecting xlwt
  Using cached xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
Collecting mysqlclient
  Using cached mysqlclient-2.2.4.tar.gz (90 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpz4buytcj get_requires_for_build_wheel /tmp/tmpzjey9mzs
       cwd: /tmp/pip-install-ahg6cupg/mysqlclient
  Complete output (27 lines):
  /bin/sh: 1: pkg-config: not found
  /bin/sh: 1: pkg-config: not found
  /bin/sh: 1: pkg-config: not found
  Trying pkg-config --exists mysqlclient
  Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
  Trying pkg-config --exists mariadb
  Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
  Trying pkg-config --exists libmariadb
  Command 'pkg-config --exists libmariadb' returned non-zero exit status 127.
  Traceback (most recent call last):
    File "/tmp/tmpz4buytcj", line 280, in <module>
      main()
    File "/tmp/tmpz4buytcj", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpz4buytcj", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-rctcsat0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
    File "/tmp/pip-build-env-rctcsat0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-rctcsat0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 318, in run_setup
      exec(code, locals())
    File "<string>", line 155, in <module>
    File "<string>", line 49, in get_config_posix
    File "<string>", line 28, in find_package_name
  Exception: Can not find valid pkg-config name.
  Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpz4buytcj get_requires_for_build_wheel /tmp/tmpzjey9mzs Check the logs for full command output.

**Comment by kingmo888** [comment]
参考 #127
大概率你mysql数据库的事儿吧。

版本方面，确实是有点乱，推荐直接clone或者docker:master，皆为最新
