### ISSUE TITLE
peers数量一多，前台就崩了

### ISSUE THREAD

**Issue by yucai100** [kingmo888/rustdesk-api-server#2]
我放到docker里运行，一次加了15台左右。
前台登录后，在/api/work就直接server error(500)，目前只能进django的后台管理。

**Comment by yucai100** [comment]
# 网页debug显示

```
KeyError at /api/work
'286098968'
Request Method:	GET
Request URL:	http://<ip>/api/work
Django Version:	5.0
Exception Type:	KeyError
Exception Value:	
'286098968'
Exception Location:	/app/api/views_front.py, line 189, in get_all_info
Raised during:	api.views_front.work
Python Executable:	/usr/local/bin/python3
Python Version:	3.11.6
Python Path:	
['/app',
 '/usr/local/lib/python311.zip',
 '/usr/local/lib/python3.11',
 '/usr/local/lib/python3.11/lib-dynload',
 '/usr/local/lib/python3.11/site-packages']
Server time:	Wed, 06 Dec 2023 17:16:56 +0800
```
# Trackback
```
Environment:


Request Method: GET
Request URL: http://10.137.231.216:21114/api/work

Django Version: 5.0
Python Version: 3.11.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'api']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']




Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/views_front.py", line 203, in work
    all_info = get_all_info()
               ^^^^^^^^^^^^^^
  File "/app/api/views_front.py", line 189, in get_all_info
    devices[peer.rid]['rust_user'] = user.username
    ^^^^^^^^^^^^^^^^^

Exception Type: KeyError at /api/work
Exception Value: '286098968'
```

# docker日志
![error](https://github.com/kingmo888/rustdesk-api-server/assets/26432807/657207f4-5b97-426e-bd6f-670272cf48cc)

**Comment by yucai100** [comment]
@kingmo888 麻烦看下上面docker日志，/api/heartbeat 也有500报错

**Comment by Simon-Leung** [comment]
> @kingmo888 麻烦看下上面docker日志，/api/heartbeat 也有500报错

我也是uuid error，我的客户端版本太旧，要1.2.2版本才有uuid字段
[Commit 72c198a add uuid to heartbeat](https://github.com/rustdesk/rustdesk/commit/72c198a1e94cc1e0242fce88f92b3f3caedcd0c3)

**Comment by kingmo888** [comment]
> > @kingmo888 麻烦看下上面docker日志，/api/heartbeat 也有500报错
> 
> 我也是uuid error，我的客户端版本太旧，要1.2.2版本才有uuid字段 [Commit 72c198a add uuid to heartbeat](https://github.com/rustdesk/rustdesk/commit/72c198a1e94cc1e0242fce88f92b3f3caedcd0c3)

我开发时的版本是1.2.3，更低版本暂不支持了，因为最新版已经1.3+了

**Comment by kingmo888** [comment]
> > @kingmo888 麻烦看下上面docker日志，/api/heartbeat 也有500报错
> 
> 我也是uuid error，我的客户端版本太旧，要1.2.2版本才有uuid字段 [Commit 72c198a add uuid to heartbeat](https://github.com/rustdesk/rustdesk/commit/72c198a1e94cc1e0242fce88f92b3f3caedcd0c3)

换句话说，印象中api使用uuid的地方应该很多，如果要兼容没有uuid的情况，可能涉及的点太多了。

**Comment by Simon-Leung** [comment]
Window当然直接升到最新版本就行，可是ubuntu16这种过期系统只能用到1.1.9版本，没法用新的

**Comment by Simon-Leung** [comment]
不过好像问题也不大，我控制端一般在win，唯一遗憾是没能在页面看哪些受控端在线，只能在控制端看连接过的

**Comment by kingmo888** [comment]
> Window当然直接升到最新版本就行，可是ubuntu16这种过期系统只能用到1.1.9版本，没法用新的

只能忍忍了，毕竟uuid这玩意作为查询条件存在还是蛮关键的。
我从1.2.3开发的时候，设计思路上就被框起来，向前兼容就会存在比较大的障碍。顶多可以兼容它不报错，但依赖uuid的功能就不好使或者错乱了，那就是一边兼容一边创造新bug。所以挺没办法的。
如果你精力的话可以考虑适配兼容以下，提交个PR
