### ISSUE TITLE
使用api方式，延迟直接飙到600-1000ms是正常的吗？

### ISSUE THREAD

**Issue by hexsen929** [kingmo888/rustdesk-api-server#43]
### What happened?
使用api方式，延迟直接飙到600-1000ms是正常的吗？
搭建的中继和ID服务器只有60ms左右。

**Comment by hexsen929** [comment]
日志如下：
`rustdesk-api-server  | Exception in thread django-main-thread:
rustdesk-api-server  | Traceback (most recent call last):
rustdesk-api-server  |   File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
rustdesk-api-server  |     self.run()
rustdesk-api-server  |   File "/usr/local/lib/python3.10/threading.py", line 946, in run
rustdesk-api-server  |     self._target(*self._args, **self._kwargs)
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
rustdesk-api-server  |     fn(*args, **kwargs)
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
rustdesk-api-server  |     self.check(display_num_errors=True)
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 486, in check
rustdesk-api-server  |     all_issues = checks.run_checks(
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
rustdesk-api-server  |     new_errors = check(app_configs=app_configs, databases=databases)
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
rustdesk-api-server  |     return check_resolver(resolver)
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
rustdesk-api-server  |     return check_method()
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 519, in check
rustdesk-api-server  |     for pattern in self.url_patterns:
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
rustdesk-api-server  |     res = instance.__dict__[self.name] = self.func(instance)
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 738, in url_patterns
rustdesk-api-server  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 47, in __get__
rustdesk-api-server  |     res = instance.__dict__[self.name] = self.func(instance)
rustdesk-api-server  |   File "/usr/local/lib/python3.10/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
rustdesk-api-server  |     return import_module(self.urlconf_name)
rustdesk-api-server  |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
rustdesk-api-server  |     return _bootstrap._gcd_import(name[level:], package, level)
rustdesk-api-server  |   File "", line 1050, in _gcd_import
rustdesk-api-server  |   File "", line 1027, in _find_and_load
rustdesk-api-server  |   File "", line 1006, in _find_and_load_unlocked
rustdesk-api-server  |   File "", line 688, in _load_unlocked
rustdesk-api-server  |   File "", line 883, in exec_module
rustdesk-api-server  |   File "", line 241, in _call_with_frames_removed
rustdesk-api-server  |   File "/rustdesk-api-server/rustdesk_server_api/urls.py", line 20, in 
rustdesk-api-server  |     from api.views import index
rustdesk-api-server  |   File "/rustdesk-api-server/api/views.py", line 23, in 
rustdesk-api-server  |     from .views_front import *
rustdesk-api-server  |   File "/rustdesk-api-server/api/views_front.py", line 24, in 
rustdesk-api-server  |     import xlwt
rustdesk-api-server  | ModuleNotFoundError: No module named 'xlwt'`

**Comment by hexsen929** [comment]
已经尝试过更换端口，还是没办法打开webui

**Comment by hexsen929** [comment]
缺少xlwt，找到问题了

**Comment by hexsen929** [comment]
udp延迟低，tcp也不应该这么高呀，而且我是家宽ddns到域名，然后本地wifi访问的内网机器。
不太懂，大家延迟是多少呀？

**Comment by hexsen929** [comment]
> 但如果你是哟给你webui延迟高，那不是我能控制的。 1、它是别人的，好像曾经是官方某个版本，不是我的。 2、料想它的所有东西都是在浏览器画出来的，所以。。

1，感谢大佬
